Repository OpenSourceRaidGuild/unimported, pull requests merged in 2021-01, with the labels that each got.

#3 installed ts-jest as devDependency
  package-lock.json
  package.json
Labels: Items: Uncommon, Quest: Main

#5 installed ts-jest as devDependency
  package-lock.json
  package.json
Labels: Items: Common, Quest: Main

#6 chore: add initial test setup
  .lintstagedrc.js
  jest.config.js
  package-lock.json
  package.json
  test/example.ts
  test/index.ts
  test/module/add.ts
  test/module/deprecated.ts
  test/module/index.ts
  test/module/join.ts
  test/packages/shared/index.js
  test/tsconfig.json
Labels: Items: Uncommon, Quest: Main, Raid: Boss, Type: Enhancement, Type: Toolchain

#7 removed and ignored lock file
  .gitignore
  package-lock.json
Labels: Items: Common, Raid: Trash Mobs, Type: Toolchain

#9 Testing - ensureArray create test
  test/ensureArray.test.ts
Labels: Status: Completed

#11 Setup tests to run on CI + Fix CI to run on PRs #10
  .github/workflows/ci.yml
Labels: Priority: Medium, Side Quest: Solo, Type: Toolchain

#13 fix: use npm i and hash package.json
  .github/workflows/ci.yml
Labels: Priority: Critical, Status: Completed

#22 Add basic integration test structure
  .gitignore
  __tests__/cli.ts
  jest.config.js
Labels: Items: Rare, Quest: Hard, Raid: Boss, Status: In Progress

#24 Test CLI output when there is an unused dependency
  __tests__/cli.ts
Labels: Quest: Main, Raid: Boss

#19 use promisify for exec and test case for error message help
  __tests__/help.ts
Labels: Quest: Main, Raid: Boss, Status: Completed

#25 Jest Coverage Configs
  .gitignore
  jest.config.js
  package.json
Labels: Items: Common, Priority: Medium, Quest: Main, Side Quest: Solo, Type: Toolchain

#26 Change integration tests to use ts-node and run the source files
  .gitignore
  .nycrc.json
  jest.config.js
  package.json
  src/__mocks__/term-size.ts
  src/__tests__/cli.ts
  src/__tests__/ensureArray.ts
  src/__tests__/help.ts
  src/__tests__/print.ts
  tsconfig.json
Labels: Items: Epic, Quest: Main, Raid: Boss, Status: Completed

#27 test: force locale to english
  src/__tests__/help.ts
Labels: Items: Uncommon, Status: Completed, Type: Enhancement

#32 test: improve cli coverage
  .gitignore
  src/__tests__/cli.ts
Labels: Quest: Main, Raid: Boss

#33 Juhanakristian
  src/__tests__/cli.ts
Labels: Items: Rare, Quest: Main, Raid: Boss
